#version: '3.8'
services:
  react-app:
    build:
      context: .  # Path ke direktori proyek
    container_name: react-app
    ports:
      - "3000:3000" # Port aplikasi React
    volumes:
      - .:/app # Mount direktori lokal ke dalam container
    command: sh -c "npm install && npm run build && npx serve -s build -l 3000"
    restart: always
    environment:
      - TZ=Asia/Jakarta # Zona waktu lokal
      - NODE_OPTIONS=--openssl-legacy-provider # Mengatasi masalah OpenSSL pada Node.js
    depends_on:
      - prometheus
      - grafana
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090" # Port untuk Prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml # File konfigurasi Prometheus
    restart: always
    environment:
      - TZ=Asia/Jakarta
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000" # Port untuk Grafana
    volumes:
      - grafana_data:/var/lib/grafana # Volume data untuk Grafana
    restart: always
    environment:
      - TZ=Asia/Jakarta
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge

volumes:
  grafana_data: # Volume untuk Grafana
