services:
  react-app:
    build: .
    container_name: react-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: sh -c "npm install && npm start"
    restart: always
    environment:
      - TZ=Asia/Jakarta

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "49001:8080" # Mengganti 49000 menjadi 49001
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock:rw
    restart: always
    privileged: true  # Opsional, tambahkan jika Jenkins memerlukan akses penuh
    environment:
      - TZ=Asia/Jakarta

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always
    environment:
      - TZ=Asia/Jakarta

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    restart: always
    environment:
      - TZ=Asia/Jakarta

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "9000:80" # NGINX reverse proxy untuk Jenkins
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - jenkins
    restart: always


volumes:
  jenkins_home:
  grafana_data:
